export enum OrderStatus {
  INQUEUE = "INQUEUE",
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED",
  REQUIRE_PRESCRIPTION_MODIFICATION = "REQUIRE_PRESCRIPTION_MODIFICATION",
  PREPARING = "PREPARING",
  READY_FOR_PICKUP = "READY_FOR_PICKUP",
  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
  DELIVERED = "DELIVERED",
  CANCELED = "CANCELED",
}
